### ISSUE TITLE
pypi.org repo

### ISSUE THREAD

**Issue by rpdelaney** [ddugovic/python-chess-annotator#49]
Hey! Since you're sort-of maintaining this, would you be willing to take over the [pypi.org](https://pypi.org/project/chess-annotator/) distribution? Then your updates would be distributed more widely.

**Comment by ddugovic** [comment]
Sure, I'll start researching how to get GitHub to push to pypi etc. to see if I can sustainably maintain that too...

**Comment by rpdelaney** [comment]
Sweet! Can you confirm your username on pypi? Then I'll add you as a maintainer.

**Comment by ddugovic** [comment]
Thanks, I just now registered as https://pypi.org/user/Toadofsky/

**Comment by rpdelaney** [comment]
Ok, I added you as a maintainer, so you should be able to cut new releases. If we can get this discord stuff sorted out maybe I can help with the CD. :) I have a server [here](https://discord.gg/TZp7yKsY) also
